 # General information
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="ZIMBA PHILANTHROPY INVESTMENTS"
ORG_DESCRIPTION="ZFI e um ativo digital criado para promover seguranca financeira, resiliencia economica e doacoes internacionais. Fortalece projetos comunitarios, facilita investimentos sociais e permite impacto positivo atraves de blockchain, garantindo transparencia, confiabilidade e acessibilidade global."
ORG_LOGO="https://raw.githubusercontent.com/Zimba2026/moeda.zfi/refs/heads/main/logo.png.png"
ORG_URL="https://zimba2026.github.io/moeda.zfi"

# Define assets
[[CURRENCIES]]
code="ZFI"
issuer="GBK2EY4GRD7ECXRUSP5DFJRHCNJEFXP2E4PCUYWS43YPAFA6IHGFX6W3"
name="Zimba Philanthropy Investments"
desc="ZFI e um ativo digital criado para promover seguranca financeira, resiliencia economica e doacoes internacionais. Fortalece projetos comunitarios, facilita investimentos sociais e permite impacto positivo atraves de blockchain, garantindo transparencia, confiabilidade e acessibilidade global."
image="https://raw.githubusercontent.com/Zimba2026/moeda.zfi/refs/heads/main/logo.png.png"
display_decimals=2
