 # General information
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="ZIMBA PHILANTHROPY INVESTMENTS"
ORG_DESCRIPTION="ZFI é um ativo digital criado para promover segurança financeira, resiliência económica e doações internacionais. Fortalece projetos comunitários, facilita investimentos sociais e permite impacto positivo através de blockchain, garantindo transparência, confiabilidade e acessibilidade global."
ORG_LOGO="https://raw.githubusercontent.com/Zimba2026/moeda.zfi/refs/heads/main/logo.png.png"
ORG_URL="https://zimba2026.github.io/moeda.zfi"

# Define assets
[[CURRENCIES]]
code="ZFI"
issuer="GBK2EY4GRD7ECXRUSP5DFJRHCNJEFXP2E4PCUYWS43YPAFA6IHGFX6W3"
name="Zimba Philanthropy Investments"
desc="ZFI é um ativo digital criado para promover segurança financeira, resiliência económica e doações internacionais. Fortalece projetos comunitários, facilita investimentos sociais e permite impacto positivo através de blockchain, garantindo transparência, confiabilidade e acessibilidade global."
image="https://raw.githubusercontent.com/Zimba2026/moeda.zfi/refs/heads/main/logo.png.png"
display_decimals=2
